ROOT = ../..
SELF = board/net
NAME = boardnet

LIB = lib$(NAME)
# INC = $(basename $(wildcard *.h))
SRC_XC = $(basename $(wildcard *.xc))
SRC_C = $(basename $(wildcard *.c))


include ${ROOT}/mk/rules.mk

include ${ROOT}/mk/tags.mk
