ROOT = ../..
SELF = board/net
NAME = boardnet

LIB = libboardnet
# INC = $(basename $(wildcard *.h))
SRC = $(basename $(wildcard *.xc)) $(basename $(wildcard *.c))


include ${ROOT}/config-xmos.mk
include ${ROOT}/mk/rules.mk
