ROOT = ../..
SELF = board/net
NAME = boardnet

LIB = lib$(NAME)
# INC = $(basename $(wildcard *.h))
SRC = $(basename $(wildcard *.xc)) $(basename $(wildcard *.c))


include ${ROOT}/mk/rules.mk

include ${ROOT}/mk/tags.mk
