ROOT = ../..
SELF = video
NAME = video

BIN = main
INC = video netconf udp
SRC = compress test 

USE = codec board/common board/compat board/cam board/chksm 

include ${ROOT}/mk/use.mk
include ${ROOT}/mk/rules.mk
