ROOT = ../..
SELF = video
NAME = video

BIN = main
INC = video netconf udp
SRC = compress test udp 

USE = codec board/common board/compat board/cam board/chksm board/net

include ${ROOT}/mk/use.mk
include ${ROOT}/mk/rules.mk
