ROOT = ../..
SELF = stream-transmitter
NAME = stream-transmitter

BIN = main
INC = format netconf udp
SRC = format udp 

USE = codec videfs board/common board/compat board/cam board/chksm board/net board/test

include ${ROOT}/mk/use.mk
include ${ROOT}/mk/xmos.mk
