ROOT = ..
SELF = codec
NAME = codec

LIB = libcmpr
HDR = config codec
INC = config
SRC = codec

include ${ROOT}/config-xmos.mk
include ${ROOT}/mk/rules.mk

include ${ROOT}/config-host.mk
include ${ROOT}/mk/rules.mk
